#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-itextomml
Version  : 1.5.2
Release  : 5
URL      : https://rubygems.org/downloads/itextomml-1.5.2.gem
Source0  : https://rubygems.org/downloads/itextomml-1.5.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.0 MPL-2.0
Requires: rubygem-itextomml-lib
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
INTRODUCTION:
This package contains the Ruby bindings for itex2MML.
It converts itex, a dialect of LaTeX, to MathML.
A summary of the LaTeX syntax supported in itex can be found at

%package lib
Summary: lib components for the rubygem-itextomml package.
Group: Libraries

%description lib
lib components for the rubygem-itextomml package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n itextomml-1.5.2
gem spec %{SOURCE0} -l --ruby > rubygem-itextomml.gemspec

%build
gem build rubygem-itextomml.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
itextomml-1.5.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/itextomml-1.5.2.gem
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/itextomml-1.5.2/gem.build_complete
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/itextomml-1.5.2/gem_make.out
/usr/lib64/ruby/gems/2.3.0/gems/itextomml-1.5.2/README
/usr/lib64/ruby/gems/2.3.0/gems/itextomml-1.5.2/ext/.RUBYARCHDIR.time
/usr/lib64/ruby/gems/2.3.0/gems/itextomml-1.5.2/ext/Makefile
/usr/lib64/ruby/gems/2.3.0/gems/itextomml-1.5.2/ext/extconf.rb
/usr/lib64/ruby/gems/2.3.0/gems/itextomml-1.5.2/ext/itex2MML.h
/usr/lib64/ruby/gems/2.3.0/gems/itextomml-1.5.2/ext/itex2MML_ruby.c
/usr/lib64/ruby/gems/2.3.0/gems/itextomml-1.5.2/ext/itex2MML_ruby.o
/usr/lib64/ruby/gems/2.3.0/gems/itextomml-1.5.2/ext/lex.yy.c
/usr/lib64/ruby/gems/2.3.0/gems/itextomml-1.5.2/ext/lex.yy.o
/usr/lib64/ruby/gems/2.3.0/gems/itextomml-1.5.2/ext/y.tab.c
/usr/lib64/ruby/gems/2.3.0/gems/itextomml-1.5.2/ext/y.tab.h
/usr/lib64/ruby/gems/2.3.0/gems/itextomml-1.5.2/ext/y.tab.o
/usr/lib64/ruby/gems/2.3.0/gems/itextomml-1.5.2/lib/itex_stringsupport.rb
/usr/lib64/ruby/gems/2.3.0/gems/itextomml-1.5.2/lib/itextomml.rb
/usr/lib64/ruby/gems/2.3.0/gems/itextomml-1.5.2/test/test_itextomml.rb
/usr/lib64/ruby/gems/2.3.0/specifications/itextomml-1.5.2.gemspec

%files lib
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/itextomml-1.5.2/itex2MML.so
/usr/lib64/ruby/gems/2.3.0/gems/itextomml-1.5.2/ext/itex2MML.so
/usr/lib64/ruby/gems/2.3.0/gems/itextomml-1.5.2/lib/itex2MML.so
